using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.ChemistryTrial;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Mono.ChemistryTrial;

[GenerateTypedNameReferences]
public sealed partial class ChemistryTrialWindow : FancyWindow
{
    [Dependency] private IGameTiming _timing = default!;

    public event Action<TimeSpan>? DurationChanged;
    public event Action<TimeSpan>? RevealDurationChanged;
    public event Action<string, bool>? CategoryToggled;
    public event Action<bool>? AllCategoriesToggled;
    public event Action? StartPressed;
    public event Action? AbortPressed;
    public event Action? DismissPressed;
    public event Action<string, string>? AnswerSubmitted;

    private readonly Dictionary<string, CheckBox> _categoryBoxes = new();
    private ChemistryTrialComponent? _trial;

    /// <summary>
    /// The latest question shown, so that inputs are only cleared when a genuinely new question appears,
    /// and not when prediction briefly rolls the state back.
    /// </summary>
    private (int Seed, int Index)? _latestQuestion;

    public ChemistryTrialWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SetupSpinBox(MinutesSpin, 99);
        SetupSpinBox(SecondsSpin, 59);

        RevealSpin.IsValid = value => value >= 0 && value <= 60;
        RevealSpin.InitDefaultButtons();
        RevealSpin.ValueChanged += _ => RevealDurationChanged?.Invoke(TimeSpan.FromSeconds(RevealSpin.Value));

        AllButton.OnPressed += _ => AllCategoriesToggled?.Invoke(true);
        NoneButton.OnPressed += _ => AllCategoriesToggled?.Invoke(false);
        StartButton.OnPressed += _ => StartPressed?.Invoke();
        AbortButton.OnPressed += _ => AbortPressed?.Invoke();
        DismissButton.OnPressed += _ => DismissPressed?.Invoke();
        SubmitButton.OnPressed += _ => Submit();
        // Enter moves on to the temperature like a form would, rather than submitting a blank temperature.
        AmountsEdit.OnTextEntered += _ =>
        {
            if (TemperatureBox.Visible)
                TemperatureEdit.GrabKeyboardFocus();
            else
                Submit();
        };
        TemperatureEdit.OnTextEntered += _ => Submit();
    }

    private void SetupSpinBox(SpinBox spinBox, int max)
    {
        spinBox.IsValid = value => value >= 0 && value <= max;
        spinBox.InitDefaultButtons();
        // The SpinBox reports invalid values through the event too, so read back the value it actually kept.
        spinBox.ValueChanged += _ => DurationChanged?.Invoke(
            TimeSpan.FromMinutes(MinutesSpin.Value) + TimeSpan.FromSeconds(SecondsSpin.Value));
    }

    private void Submit()
    {
        if (_trial is not { Phase: ChemistryTrialPhase.Running, Revealing: false })
            return;

        AnswerSubmitted?.Invoke(AmountsEdit.Text, TemperatureEdit.Text);
    }

    public void UpdateState(ChemistryTrialComponent trial, ChemistryTrialCatalog catalog)
    {
        _trial = trial;

        ConfigBox.Visible = trial.Phase == ChemistryTrialPhase.Idle;
        RunBox.Visible = trial.Phase == ChemistryTrialPhase.Running;
        ResultsBox.Visible = trial.Phase == ChemistryTrialPhase.Finished;

        switch (trial.Phase)
        {
            case ChemistryTrialPhase.Idle:
                UpdateConfiguration(trial, catalog);
                break;
            case ChemistryTrialPhase.Running:
                UpdateQuestion(trial, catalog);
                break;
            case ChemistryTrialPhase.Finished:
                PassedLabel.Text = Loc.GetString("chemistry-trial-results-passed", ("count", trial.Passed));
                FailedLabel.Text = Loc.GetString("chemistry-trial-results-failed", ("count", trial.Failed));
                TotalLabel.Text = Loc.GetString("chemistry-trial-results-total", ("count", trial.Passed + trial.Failed));
                break;
        }

        UpdateTimers();
    }

    private void UpdateConfiguration(ChemistryTrialComponent trial, ChemistryTrialCatalog catalog)
    {
        // Values are only written when they differ, so a value being typed is never stomped on.
        var minutes = (int) trial.Duration.TotalMinutes;
        var seconds = trial.Duration.Seconds;
        if (MinutesSpin.Value != minutes)
            MinutesSpin.OverrideValue(minutes);
        if (SecondsSpin.Value != seconds)
            SecondsSpin.OverrideValue(seconds);

        var reveal = (int) trial.RevealDuration.TotalSeconds;
        if (RevealSpin.Value != reveal)
            RevealSpin.OverrideValue(reveal);

        if (!_categoryBoxes.Keys.SequenceEqual(catalog.Categories))
            RebuildCategories(catalog);

        foreach (var (category, box) in _categoryBoxes)
        {
            var enabled = !trial.DisabledCategories.Contains(category);
            if (box.Pressed != enabled)
                box.Pressed = enabled;
        }

        var eligible = catalog.GetEligible(trial.DisabledCategories).Count;
        EligibleLabel.Text = Loc.GetString("chemistry-trial-eligible", ("count", eligible));
        StartButton.Disabled = eligible == 0;
    }

    private void RebuildCategories(ChemistryTrialCatalog catalog)
    {
        CategoryGrid.RemoveAllChildren();
        _categoryBoxes.Clear();

        foreach (var category in catalog.Categories)
        {
            var count = catalog.Recipes.Count(r => r.Categories.Contains(category));
            var box = new CheckBox
            {
                Text = Loc.GetString("chemistry-trial-category", ("category", category), ("count", count)),
                HorizontalExpand = true,
            };
            box.OnToggled += args => CategoryToggled?.Invoke(category, args.Pressed);
            CategoryGrid.AddChild(box);
            _categoryBoxes.Add(category, box);
        }
    }

    private void UpdateQuestion(ChemistryTrialComponent trial, ChemistryTrialCatalog catalog)
    {
        ScoreLabel.Text = Loc.GetString("chemistry-trial-score", ("passed", trial.Passed), ("failed", trial.Failed));

        if (!catalog.TryGetRecipe(trial.QuestionReaction, out var recipe))
            return;

        var toRecipe = trial.QuestionDirection == ChemistryTrialDirection.ProductToRecipe;
        TemperatureBox.Visible = toRecipe;

        // Editability must be applied before focusing: a LineEdit only starts text input when it gains focus while editable.
        SetEditable(AmountsEdit, !trial.Revealing);
        SetEditable(TemperatureEdit, !trial.Revealing);
        SubmitButton.Disabled = trial.Revealing;
        RevealPanel.Visible = trial.Revealing;

        var question = (trial.RunSeed, trial.QuestionIndex);
        if (_latestQuestion is not { } latest || latest.Seed != question.RunSeed || latest.Index < question.QuestionIndex)
        {
            _latestQuestion = question;
            AmountsEdit.Text = string.Empty;
            TemperatureEdit.Text = string.Empty;
            AmountsEdit.GrabKeyboardFocus();
        }
        if (toRecipe)
        {
            PromptLabel.Text = Loc.GetString("chemistry-trial-prompt-recipe");
            QuestionLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("chemistry-trial-question-recipe",
                ("product", FormattedMessage.EscapeText(recipe.Label)))));
            AmountsLabel.Text = Loc.GetString("chemistry-trial-reactants");
            AmountsEdit.PlaceHolder = Loc.GetString("chemistry-trial-reactants-placeholder");
        }
        else
        {
            PromptLabel.Text = Loc.GetString("chemistry-trial-prompt-products");
            QuestionLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("chemistry-trial-question-products",
                ("reactants", FormattedMessage.EscapeText(ChemistryTrialCatalog.FormatAmounts(recipe.Reactants))),
                ("temperature", FormattedMessage.EscapeText(ChemistryTrialCatalog.FormatTemperature(recipe))),
                ("mixing", FormatMixing(recipe)))));
            AmountsLabel.Text = Loc.GetString("chemistry-trial-products");
            AmountsEdit.PlaceHolder = Loc.GetString("chemistry-trial-products-placeholder");
        }

        if (trial.Revealing)
        {
            RevealTitle.Text = Loc.GetString("chemistry-trial-reveal-title");
            RevealLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("chemistry-trial-reveal",
                ("reactants", FormattedMessage.EscapeText(ChemistryTrialCatalog.FormatAmounts(recipe.Reactants))),
                ("products", FormattedMessage.EscapeText(ChemistryTrialCatalog.FormatAmounts(recipe.Products))),
                ("label", FormattedMessage.EscapeText(recipe.Label)),
                ("temperature", FormattedMessage.EscapeText(ChemistryTrialCatalog.FormatTemperature(recipe))),
                ("mixing", FormatMixing(recipe)),
                ("answer", FormattedMessage.EscapeText(trial.LastAnswer)))));
        }
    }

    /// <summary>
    /// Sets whether a field accepts input. A field that becomes editable while already focused is refocused,
    /// since a LineEdit only starts text input when it gains focus while editable,
    /// which would otherwise leave it focused but deaf to typing.
    /// </summary>
    private static void SetEditable(LineEdit edit, bool editable)
    {
        if (edit.Editable == editable)
            return;

        edit.Editable = editable;
        if (editable && edit.HasKeyboardFocus())
        {
            edit.ReleaseKeyboardFocus();
            edit.GrabKeyboardFocus();
        }
    }

    private static string FormatMixing(ChemistryTrialRecipe recipe)
    {
        return recipe.Mixing.Count == 0
            ? Loc.GetString("chemistry-trial-mixing-none")
            : FormattedMessage.EscapeText(string.Join(", ", recipe.Mixing));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateTimers();
    }

    private void UpdateTimers()
    {
        if (_trial is not { Phase: ChemistryTrialPhase.Running })
            return;

        var now = _timing.CurTime;
        var remaining = _trial.EndTime - now;
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        TimeLabel.Text = Loc.GetString("chemistry-trial-time-left",
            ("time", $"{(int) remaining.TotalMinutes}:{remaining.Seconds:D2}"));

        if (_trial.Revealing)
        {
            var reveal = _trial.RevealEndTime - now;
            RevealCountdown.Text = Loc.GetString("chemistry-trial-reveal-countdown",
                ("seconds", Math.Max(0, Math.Ceiling(reveal.TotalSeconds))));
        }
    }
}
